---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: Testing


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:

  # Runs on master Branch and Tags
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+*'


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  testing:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:

      # ------------------------------------------------------------
      # Checkout repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Show bash versions
        shell: bash
        run: |
          bash --version

      # ------------------------------------------------------------
      # Test
      # ------------------------------------------------------------
      - name: Install
        shell: bash
        run: |
          sudo make install

      - name: Test
        shell: bash
        run: |
          autorunner
